version: '3.5'
services:
  main_proxy:
    container_name: main_proxy
    build: ./rippleginx
    volumes:
      - ./keys/:/keys/
    ports:
      - 80:80
      - 443:443
    restart: on-failure