version: '3.5'
services:
  main_proxy:
    container_name: main_proxy
    image: nginx
    volumes:
      - ./servers/:/etc/nginx/conf.d/
    ports:
      - 80:80
      - 443:443
    restart: on-failure