version: '3.5'
services:
  web:
    container_name: web
    build: ./rippleginx
    volumes:
      - ./keys/:/keys/
    environment:
      - DOMAIN
    depends_on:
      - hanayo
      - lets
      - peppy
      - old_frontend
      - avatar_server
    ports:
      - 80:80
      - 443:443
    restart: on-failure

  redis:
    container_name: redis
    image: redis
    volumes:
      - redis_vol:/data
    restart: on-failure

volumes:
  redis_vol:
