version: '3.5'
services:
  peppy:
    container_name: ID_peppy
    image: shobble/pep.py
    environment:
      - MYSQL_ROOT_PASSWORD
      - CIKEY
    depends_on:
      - redis
      - db
    ports:
      - ID_01:5001
    restart: on-failure

  lets:
    container_name: ID_lets
    image: shobble/lets
    environment:
      - OSU_API_KEY=$OSUKEY
      - DB_PASSWORD=$MYSQL_ROOT_PASSWORD
      - BANCHO_API_KEY=$CIKEY
      - CHEESEGULL_API_URL=https://storage.ripple.moe/api
    volumes:
      - ./lets:/let.s/.data
    depends_on:
      - redis
      - db
    ports:
      - ID_02:5002
    restart: on-failure

  hanayo:
    container_name: ID_hanayo
    image: shobble/hanayo
    environment:
      - DOMAIN
      - MYSQL_ROOT_PASSWORD
      - APISECRET
    volumes:
      - ./avatars/:/avatars
    depends_on:
      - redis
      - db
      - rippleapi
    ports:
      - ID_03:45221
    restart: on-failure

  rippleapi:
    container_name: ID_rippleapi
    image: shobble/rippleapi
    environment:
      - MYSQL_ROOT_PASSWORD
      - APISECRET
    depends_on:
      - redis
      - db
    ports:
      - ID_04:40001
    restart: on-failure

  avatar_server:
    container_name: ID_avatar_server
    image: shobble/avatar-server
    volumes:
      - ./avatars/:/avatar_server/avatars
    ports:
      - ID_05:5000
    restart: on-failure

  db:
    container_name: ID_db
    image: shobble/rippledb
    environment:
      - MYSQL_ROOT_PASSWORD
    volumes:
      - ./db_data/:/var/lib/mysql
    restart: on-failure

  redis:
    container_name: ID_redis
    image: redis
    volumes:
      - ./redis/:/data
    restart: on-failure

